# Generated by Django 3.2.6 on 2021-09-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='no_address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(default='No hobbies'),
            preserve_default=False,
        ),
    ]
